Repository scseong/motitube, pull requests merged in 2023-12, with the labels that each got.

#6 feat: YouTube API Mock 데이터 생성
  public/videos/video.json
  public/videos/videos.json
Labels: 기능

#12 feat: 상세 페이지 UI
  .eslintrc
  package.json
  src/components/Channel/YoutubeChannel.jsx
  src/components/Channel/styles.js
  src/components/Detail/Sidebar.jsx
  src/components/Detail/VideoInfo.jsx
  src/components/Detail/VideoPlayer.jsx
  src/components/Detail/index.js
  src/components/Detail/styles.js
  src/components/DetailPost/Comments.jsx
  src/components/DetailPost/PostInfo.jsx
  src/components/DetailPost/RecommendMovies.jsx
  src/components/DetailPost/styles.js
  src/pages/Detail.jsx
  src/styles/GlobalStyles.js
  yarn.lock
Labels: 버그, UI

#14 config: eslint parser를 @babel/eslint-parser변경
  .eslintrc
  package.json
  yarn.lock
Labels: 설정

#21 feat: mock 데이터 대신 API 응답 받아 데이터 가공
  src/api/base.js
  src/api/post.js
  src/api/video.js
  src/components/Detail/Sidebar.jsx
  src/components/Detail/VideoInfo.jsx
  src/components/Detail/styles.js
  src/components/DetailPost/Comments.jsx
  src/components/DetailPost/index.js
  src/components/DetailPost/styles.js
  src/pages/Detail.jsx
Labels: 기능

#32 feat: 상세페이지 댓글 기능 구현, 각 버튼 별 컴포넌트 표시
  src/api/base.js
  src/api/comment.js
  src/api/post.js
  src/api/video.js
  src/components/Detail/FetchLoader.jsx
  src/components/Detail/Sidebar.jsx
  src/components/Detail/VideoInfo.jsx
  src/components/Detail/VideoPlayer.jsx
  src/components/Detail/index.js
  src/components/Detail/styles.js
  src/components/DetailPost/Comment.jsx
  src/components/DetailPost/Comments.jsx
  src/components/DetailPost/RecommendMovie.jsx
  src/components/DetailPost/RecommendMovies.jsx
  src/components/DetailPost/styles.js
  src/hooks/useComment.js
  src/pages/Detail.jsx
  src/util/date.js
Labels: UI, 기능

#38 Feat/home
  src/components/Homecomponents/Card.jsx
Labels: 기능

#43 Feat/home :등록순정렬,UI추가
  src/api/post.js
  src/components/Common/styles.js
  src/components/Homecomponents/Card.jsx
  src/components/Homecomponents/Dashboad.jsx
  src/components/Homecomponents/Slide.jsx
  src/components/Homecomponents/styles.js
Labels: UI, 기능

#44 feat: 댓글 이미지 수정 & 댓글 업데이트
  src/api/comment.js
  src/components/Detail/VideoPlayer.jsx
  src/components/DetailPost/Comment.jsx
  src/components/DetailPost/Comments.jsx
  src/components/DetailPost/PostInfo.jsx
  src/components/DetailPost/styles.js
  src/hooks/useComment.js
  src/styles/GlobalStyles.js
Labels: 기능
